import { prisma } from "@/lib/db";
import { logger } from "@/lib/utils";

import type { DailyUsage, TopDomain, UsageOverview, AnalyticsData } from "./analytics.types";

// ============================================================================
// Analytics Service
//
// Aggregates API usage data for the analytics dashboard.
// All queries are scoped to the authenticated user's API keys.
// ============================================================================

/**
 * Get the full analytics dashboard data for a user.
 */
export async function getAnalytics(
  userId: string,
  startDate?: Date,
  endDate?: Date
): Promise<AnalyticsData> {
  const [overview, dailyUsage, topDomains] = await Promise.all([
    getUsageOverview(userId),
    getDailyUsage(userId, startDate, endDate),
    getTopDomains(userId, startDate, endDate),
  ]);

  return { overview, dailyUsage, topDomains };
}

/**
 * Get the usage overview (stat cards) for the dashboard.
 */
export async function getUsageOverview(userId: string): Promise<UsageOverview> {
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  // Run all queries in parallel
  const [totalPreviews, requestsToday, activeKeys, cacheStats] = await Promise.all([
    // Total previews generated by this user
    prisma.preview.count({ where: { userId } }),

    // Requests made today across all keys
    prisma.apiUsage.count({
      where: {
        apiKey: { userId },
        createdAt: { gte: today },
      },
    }),

    // Active API keys count
    prisma.apiKey.count({
      where: { userId, revokedAt: null },
    }),

    // Cache hit rate (last 7 days)
    prisma.apiUsage.groupBy({
      by: ["cached"],
      where: {
        apiKey: { userId },
        createdAt: { gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
      },
      _count: true,
    }),
  ]);

  // Calculate cache hit rate
  const totalRequests = cacheStats.reduce((sum, s) => sum + s._count, 0);
  const cachedRequests = cacheStats.find((s) => s.cached === true)?._count ?? 0;
  const cacheHitRate = totalRequests > 0
    ? Math.round((cachedRequests / totalRequests) * 100)
    : 0;

  // Get user's plan for remaining quota calculation
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { plan: true },
  });

  const planLimits: Record<string, number> = {
    free: 100,
    pro: 10000,
    enterprise: 100000,
  };
  const dailyLimit = planLimits[user?.plan ?? "free"] ?? 100;
  const remainingQuota = Math.max(0, dailyLimit - requestsToday);

  return {
    totalPreviews,
    requestsToday,
    remainingQuota,
    activeKeys,
    cacheHitRate,
  };
}

/**
 * Get daily usage breakdown for a date range.
 */
export async function getDailyUsage(
  userId: string,
  startDate?: Date,
  endDate?: Date
): Promise<DailyUsage[]> {
  const start = startDate ?? new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const end = endDate ?? new Date();

  try {
    const results = await prisma.$queryRaw<
      Array<{
        date: Date;
        total_requests: bigint;
        successful_requests: bigint;
        cached_requests: bigint;
        avg_response_time: number | null;
      }>
    >`
      SELECT 
        DATE(au.created_at) as date,
        COUNT(*)::bigint as total_requests,
        COUNT(*) FILTER (WHERE au.status_code = 200)::bigint as successful_requests,
        COUNT(*) FILTER (WHERE au.cached = true)::bigint as cached_requests,
        AVG(au.response_time)::float as avg_response_time
      FROM api_usage au
      JOIN api_keys ak ON au.api_key_id = ak.id
      WHERE ak.user_id = ${userId}::uuid
        AND au.created_at >= ${start}
        AND au.created_at <= ${end}
      GROUP BY DATE(au.created_at)
      ORDER BY date DESC
    `;

    return results.map((r) => ({
      date: r.date.toISOString().split("T")[0] as string,
      totalRequests: Number(r.total_requests),
      successfulRequests: Number(r.successful_requests),
      cachedRequests: Number(r.cached_requests),
      avgResponseTime: Math.round(r.avg_response_time ?? 0),
    }));
  } catch (error) {
    logger.error("Failed to get daily usage", {
      userId,
      error: error instanceof Error ? error.message : "Unknown",
    });
    return [];
  }
}

/**
 * Get the top domains by request count.
 */
export async function getTopDomains(
  userId: string,
  startDate?: Date,
  endDate?: Date,
  limit: number = 10
): Promise<TopDomain[]> {
  const start = startDate ?? new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  const end = endDate ?? new Date();

  const results = await prisma.preview.groupBy({
    by: ["domain"],
    where: {
      userId,
      createdAt: {
        gte: start,
        lte: end,
      },
    },
    _count: { domain: true },
    orderBy: { _count: { domain: "desc" } },
    take: limit,
  });

  return results.map((r) => ({
    domain: r.domain,
    count: r._count.domain,
  }));
}
